In [1]:
import numpy as np
from QR import getQR

In [2]:
matrix = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)

In [3]:
Q, R = getQR(matrix)

In [6]:
print((Q @ Q.T).astype(int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [7]:
print((Q @ R).astype(int))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
