In [1]:
import numpy as np


In [2]:
from LUP import findLUP

In [3]:
matrix = np.array(
    [
        [ 4, 6, 71, 1],
        [ 1, 0, 8, 1],
        [4, 61, 71, 1],
        [ 4, 6, 7, 13],
    ]
)

In [4]:
matrix.shape

(4, 4)

In [5]:
sing_val = np.linalg.svd(matrix).S


sing_val.max() / sing_val.min()

394.6374923531631

In [6]:
P, L, U = findLUP(matrix)

In [7]:
print(P @ matrix)

[[ 4  6 71  1]
 [ 4 61 71  1]
 [ 4  6  7 13]
 [ 1  0  8  1]]


In [8]:
print((L @ U).astype(int))

[[ 4  6 71  1]
 [ 4 61 71  1]
 [ 4  6  7 13]
 [ 1  0  8  1]]


In [9]:
print(L)

[[ 1.          0.          0.          0.        ]
 [ 1.          1.          0.          0.        ]
 [ 1.          0.          1.          0.        ]
 [ 0.25       -0.02727273  0.15234375  1.        ]]


In [10]:
print(U)

[[  4.         6.        71.         1.      ]
 [  0.        55.         0.         0.      ]
 [  0.         0.       -64.        12.      ]
 [  0.         0.         0.        -1.078125]]


In [11]:
def generate_well_conditioned_matrix(n, cond_number=10):

    A_rand = np.random.randn(n, n)
    U, _ = np.linalg.qr(A_rand)
    B_rand = np.random.randn(n, n)
    V, _ = np.linalg.qr(B_rand)

    singular_values = np.linspace(1, 1/cond_number, n)  # равномерно убывающие значения

    Sigma = np.diag(singular_values)
    A = U @ Sigma @ V.T

    return A


matrix = generate_well_conditioned_matrix(5 * 10 ** 3, cond_number=100)


In [12]:
P, L, U = findLUP(matrix)


In [13]:
np.allclose(P @ matrix, L @ U, rtol=1e-03, atol=1e-03)

True