In [1]:
import numpy as np
from LDLT import getLDLT

In [2]:
matrix = np.array(
    [
        [4, 12, -16],
        [12, 37, -43],
        [-16, -43, 98]
    ]
)

In [3]:
L, D = getLDLT(matrix)

In [4]:
print(L)

[[ 1.  0.  0.]
 [ 3.  1.  0.]
 [-4.  5.  1.]]


In [5]:
print(D)

[[4. 0. 0.]
 [0. 1. 0.]
 [0. 0. 9.]]


In [6]:
check = L @ D @ L.T

In [7]:
assert np.allclose(check, matrix)

In [8]:
def generate_positive_definite_matrix(n):

    random_matrix = np.random.rand(n, n)

    A = np.dot(random_matrix.T, random_matrix)

    A += np.eye(n) * 1e-6

    return A

In [9]:
matrix = generate_positive_definite_matrix(10 ** 4)

In [10]:
L, D = getLDLT(matrix)

In [11]:
assert np.allclose(L @ D @ L.T, matrix)